### PR TITLE
Minor naming updates and small changes to the scripts

### PR DESCRIPTION
**Pull request by riclarsson**
Alex, I made some small updates having a quick look at this today.  I think there's something wrong with the TRE05 model as well from this.  I am going to have more of a look tomorrow.  I am also running the model without the updates that comes from Oliver, so I'll need to talk to him about those.

I've changed so that you can put your AER catalog in the same folder as these python files without messing with git, or at least just have it in the path that you are reading from (e.g., add it to your path in your bashrc or mac equivalent).  You had it hard-coded to your scratch directory before.  This makes it possible for us both to work with this without having to manually maintain different paths.

I also changed the names of the outputs from AER model to be similar to what the other two are doing.

I also added the output directory to the ignore list.

All in all just small things, but just letting you know I am having a look.  Finally.

### CODE REVIEW

**Comment by riclarsson** [comment]
Also, I think for AER you should apply the frequency scaling and mirroring.  Perhaps not the latter.  But this can be changed back...

**Comment by obobryshev** [comment]
Hi Richard,

first of all, I'm sorry for such a late reply. I have missed that you created a pull request until yesterday. 

`plot_any_range.py` I added a function to read and plot results quickly.

Based on the plots TRE05 and MPM2020 agree very well. But AER is 10K different on the frequencies higher than 80 GHz.

Also, when I use mirroring option for AER, I receive the following error message.
```iy_AERm.py
Error is found at:
	/home/sasha/progs/git/arts/src/m_checked.cc:818
Please follow these instructions to correct your error:
Cutoff only possible with symmetric mirroring types
```

For MPM2020, I don't have AddPredifinedO2MPM2020 in the propmat_clearsky. And abs_xsec_per_species requires this function.
```iy_MPM2020m.py
ws.abs_xsec_per_speciesAddPredefinedO2MPM2020()
ws.propmat_clearskyAddPredefinedO2MPM2020()
```

**Comment by riclarsson** [comment]
@obobryshev You cannot use cutoff with manual line mixing.  In fact, you shouldn't use cutoff with any other species but water, and only if you use AER continua.  The cutoff in ARTS is bad, it destroys the absorption profile...  for line mixing in particular, this destruction means you **_will_** have negative absorption if you use it.

Edit:  Because it looks like it's not the mirroring but the cutoff that's the problem.

**Comment by obobryshev** [comment]
@riclarsson I think there is a "bug" in the current arts-master branch. ARTS-calculated Tbs are now hugely incosistent between different versions/branches, when I run TestMetMM.arts script `controlfiles/instruments/metmm/TestMetMM.arts`.
Branches `v2.4.x` and `before-newlinerecord`  run without errors.
Current `master` branch gives results that are off by 30-60K.
I asked Oliver about this. Can you please have a look as well?

Edit:
- AddPredifinedO2MPM2020 function works fine now.
- I don't use the cutoff for oxygen. At least I think so. I don't know how to switch it off other than current implementation.

**Pull request merged**
